
package pe.bf.ws.mail;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Mail", targetNamespace = "http://ws.mail.bf.pe/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Mail {


    /**
     * 
     * @param cc
     * @param nombreArchivo
     * @param bcc
     * @param archivo
     * @param asunto
     * @param to
     * @param mensaje
     * @return
     *     returns pe.bf.ws.mail.Respuesta
     */
    @WebMethod
    @WebResult(name = "respuesta", targetNamespace = "")
    @RequestWrapper(localName = "enviarMailAutonomia", targetNamespace = "http://ws.mail.bf.pe/", className = "pe.bf.ws.mail.EnviarMailAutonomia")
    @ResponseWrapper(localName = "enviarMailAutonomiaResponse", targetNamespace = "http://ws.mail.bf.pe/", className = "pe.bf.ws.mail.EnviarMailAutonomiaResponse")
    @Action(input = "http://ws.mail.bf.pe/Mail/enviarMailAutonomiaRequest", output = "http://ws.mail.bf.pe/Mail/enviarMailAutonomiaResponse")
    public Respuesta enviarMailAutonomia(
        @WebParam(name = "to", targetNamespace = "")
        List<String> to,
        @WebParam(name = "cc", targetNamespace = "")
        List<String> cc,
        @WebParam(name = "bcc", targetNamespace = "")
        List<String> bcc,
        @WebParam(name = "asunto", targetNamespace = "")
        String asunto,
        @WebParam(name = "mensaje", targetNamespace = "")
        String mensaje,
        @WebParam(name = "archivo", targetNamespace = "")
        byte[] archivo,
        @WebParam(name = "nombreArchivo", targetNamespace = "")
        String nombreArchivo);

    /**
     * 
     * @param cc
     * @param nombreArchivo
     * @param bcc
     * @param archivo
     * @param asunto
     * @param to
     * @param mensaje
     * @return
     *     returns pe.bf.ws.mail.Respuesta
     */
    @WebMethod
    @WebResult(name = "respuesta", targetNamespace = "")
    @RequestWrapper(localName = "enviarMailMonitoreoReclamos", targetNamespace = "http://ws.mail.bf.pe/", className = "pe.bf.ws.mail.EnviarMailMonitoreoReclamos")
    @ResponseWrapper(localName = "enviarMailMonitoreoReclamosResponse", targetNamespace = "http://ws.mail.bf.pe/", className = "pe.bf.ws.mail.EnviarMailMonitoreoReclamosResponse")
    @Action(input = "http://ws.mail.bf.pe/Mail/enviarMailMonitoreoReclamosRequest", output = "http://ws.mail.bf.pe/Mail/enviarMailMonitoreoReclamosResponse")
    public Respuesta enviarMailMonitoreoReclamos(
        @WebParam(name = "to", targetNamespace = "")
        List<String> to,
        @WebParam(name = "cc", targetNamespace = "")
        List<String> cc,
        @WebParam(name = "bcc", targetNamespace = "")
        List<String> bcc,
        @WebParam(name = "asunto", targetNamespace = "")
        String asunto,
        @WebParam(name = "mensaje", targetNamespace = "")
        String mensaje,
        @WebParam(name = "archivo", targetNamespace = "")
        byte[] archivo,
        @WebParam(name = "nombreArchivo", targetNamespace = "")
        String nombreArchivo);

    /**
     * 
     * @param cc
     * @param nombreArchivo
     * @param bcc
     * @param archivo
     * @param asunto
     * @param to
     * @param mensaje
     * @return
     *     returns pe.bf.ws.mail.Respuesta
     */
    @WebMethod
    @WebResult(name = "respuesta", targetNamespace = "")
    @RequestWrapper(localName = "enviarMailBloqueoDefinitivo", targetNamespace = "http://ws.mail.bf.pe/", className = "pe.bf.ws.mail.EnviarMailBloqueoDefinitivo")
    @ResponseWrapper(localName = "enviarMailBloqueoDefinitivoResponse", targetNamespace = "http://ws.mail.bf.pe/", className = "pe.bf.ws.mail.EnviarMailBloqueoDefinitivoResponse")
    @Action(input = "http://ws.mail.bf.pe/Mail/enviarMailBloqueoDefinitivoRequest", output = "http://ws.mail.bf.pe/Mail/enviarMailBloqueoDefinitivoResponse")
    public Respuesta enviarMailBloqueoDefinitivo(
        @WebParam(name = "to", targetNamespace = "")
        List<String> to,
        @WebParam(name = "cc", targetNamespace = "")
        List<String> cc,
        @WebParam(name = "bcc", targetNamespace = "")
        List<String> bcc,
        @WebParam(name = "asunto", targetNamespace = "")
        String asunto,
        @WebParam(name = "mensaje", targetNamespace = "")
        String mensaje,
        @WebParam(name = "archivo", targetNamespace = "")
        byte[] archivo,
        @WebParam(name = "nombreArchivo", targetNamespace = "")
        String nombreArchivo);

    /**
     * 
     * @param cc
     * @param nombreArchivo
     * @param bcc
     * @param archivo
     * @param asunto
     * @param to
     * @param mensaje
     * @return
     *     returns pe.bf.ws.mail.Respuesta
     */
    @WebMethod
    @WebResult(name = "respuesta", targetNamespace = "")
    @RequestWrapper(localName = "enviarMailNotificacion", targetNamespace = "http://ws.mail.bf.pe/", className = "pe.bf.ws.mail.EnviarMailNotificacion")
    @ResponseWrapper(localName = "enviarMailNotificacionResponse", targetNamespace = "http://ws.mail.bf.pe/", className = "pe.bf.ws.mail.EnviarMailNotificacionResponse")
    @Action(input = "http://ws.mail.bf.pe/Mail/enviarMailNotificacionRequest", output = "http://ws.mail.bf.pe/Mail/enviarMailNotificacionResponse")
    public Respuesta enviarMailNotificacion(
        @WebParam(name = "to", targetNamespace = "")
        List<String> to,
        @WebParam(name = "cc", targetNamespace = "")
        List<String> cc,
        @WebParam(name = "bcc", targetNamespace = "")
        List<String> bcc,
        @WebParam(name = "asunto", targetNamespace = "")
        String asunto,
        @WebParam(name = "mensaje", targetNamespace = "")
        String mensaje,
        @WebParam(name = "archivo", targetNamespace = "")
        byte[] archivo,
        @WebParam(name = "nombreArchivo", targetNamespace = "")
        String nombreArchivo);

    /**
     * 
     * @param mensaje
     * @param telefono
     * @param nombre
     * @param email
     * @param dni
     * @return
     *     returns pe.bf.ws.mail.Respuesta
     */
    @WebMethod
    @WebResult(name = "respuesta", targetNamespace = "")
    @RequestWrapper(localName = "enviaSimulacionPV", targetNamespace = "http://ws.mail.bf.pe/", className = "pe.bf.ws.mail.EnviaSimulacionPV")
    @ResponseWrapper(localName = "enviaSimulacionPVResponse", targetNamespace = "http://ws.mail.bf.pe/", className = "pe.bf.ws.mail.EnviaSimulacionPVResponse")
    @Action(input = "http://ws.mail.bf.pe/Mail/enviaSimulacionPVRequest", output = "http://ws.mail.bf.pe/Mail/enviaSimulacionPVResponse")
    public Respuesta enviaSimulacionPV(
        @WebParam(name = "email", targetNamespace = "")
        String email,
        @WebParam(name = "nombre", targetNamespace = "")
        String nombre,
        @WebParam(name = "dni", targetNamespace = "")
        int dni,
        @WebParam(name = "telefono", targetNamespace = "")
        String telefono,
        @WebParam(name = "mensaje", targetNamespace = "")
        String mensaje);

    /**
     * 
     * @param cc
     * @param nombreArchivo
     * @param bcc
     * @param archivo
     * @param asunto
     * @param to
     * @param mensaje
     * @return
     *     returns pe.bf.ws.mail.Respuesta
     */
    @WebMethod
    @WebResult(name = "respuesta", targetNamespace = "")
    @RequestWrapper(localName = "enviarMail", targetNamespace = "http://ws.mail.bf.pe/", className = "pe.bf.ws.mail.EnviarMail")
    @ResponseWrapper(localName = "enviarMailResponse", targetNamespace = "http://ws.mail.bf.pe/", className = "pe.bf.ws.mail.EnviarMailResponse")
    @Action(input = "http://ws.mail.bf.pe/Mail/enviarMailRequest", output = "http://ws.mail.bf.pe/Mail/enviarMailResponse")
    public Respuesta enviarMail(
        @WebParam(name = "to", targetNamespace = "")
        List<String> to,
        @WebParam(name = "cc", targetNamespace = "")
        List<String> cc,
        @WebParam(name = "bcc", targetNamespace = "")
        List<String> bcc,
        @WebParam(name = "asunto", targetNamespace = "")
        String asunto,
        @WebParam(name = "mensaje", targetNamespace = "")
        String mensaje,
        @WebParam(name = "archivo", targetNamespace = "")
        byte[] archivo,
        @WebParam(name = "nombreArchivo", targetNamespace = "")
        String nombreArchivo);

}
