
package pe.bf.ws.mail;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MailService", targetNamespace = "http://ws.mail.bf.pe/")
public class MailService extends Service
{
    private final static URL MAILSERVICE_WSDL_LOCATION;
    private final static WebServiceException MAILSERVICE_EXCEPTION;
    private final static QName MAILSERVICE_QNAME = new QName("http://ws.mail.bf.pe/", "MailService");
    private static final Logger logger = Logger.getLogger(MailService.class.getName());

    static {
        URL url = null;
        WebServiceException e = null;
        try {
        	URL baseUrl = MailService.class.getResource(".");
            url = new URL(baseUrl, System.getProperty("SERVER_WS3") + "/MailWS_V1/MailService?wsdl");
        } catch (MalformedURLException ex) {
        	logger.warning("Failed to create URL for the wsdl Location: '" + System.getProperty("SERVER_WS3") + "/MailWS_V1/MailService?wsdl', retrying as a local file");
        	logger.warning(ex.getMessage());
            e = new WebServiceException(ex);
        }
        MAILSERVICE_WSDL_LOCATION = url;
        MAILSERVICE_EXCEPTION = e;
    }

    public MailService() {
        super(__getWsdlLocation(), MAILSERVICE_QNAME);
    }

    public MailService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MAILSERVICE_QNAME, features);
    }

    public MailService(URL wsdlLocation) {
        super(wsdlLocation, MAILSERVICE_QNAME);
    }

    public MailService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MAILSERVICE_QNAME, features);
    }

    public MailService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MailService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Mail
     */
    @WebEndpoint(name = "MailServicePort")
    public Mail getMailServicePort() {
        return super.getPort(new QName("http://ws.mail.bf.pe/", "MailServicePort"), Mail.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Mail
     */
    @WebEndpoint(name = "MailServicePort")
    public Mail getMailServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.mail.bf.pe/", "MailServicePort"), Mail.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MAILSERVICE_EXCEPTION!= null) {
            throw MAILSERVICE_EXCEPTION;
        }
        return MAILSERVICE_WSDL_LOCATION;
    }

}
